/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-fire-front', 'bg-fire-background',
    'bg-water-front', 'bg-water-background',
    'bg-grass-front', 'bg-grass-background',
    'bg-electric-front', 'bg-electric-background',
    'bg-ice-front', 'bg-ice-background',
    'bg-normal-front', 'bg-normal-background',
    'bg-fighting-front', 'bg-fighting-background',
    'bg-poison-front', 'bg-poison-background',
    'bg-ground-front', 'bg-ground-background',
    'bg-flying-front', 'bg-flying-background',
    'bg-psychic-front', 'bg-psychic-background',
    'bg-bug-front', 'bg-bug-background',
    'bg-rock-front', 'bg-rock-background',
    'bg-ghost-front', 'bg-ghost-background',
    'bg-dragon-front', 'bg-dragon-background',

    'hover:from-fire-front', 'hover:to-fire-background',
    'hover:from-water-front', 'hover:to-water-background',
    'hover:from-grass-front', 'hover:to-grass-background',
    'hover:from-electric-front', 'hover:to-electric-background',
    'hover:from-ice-front', 'hover:to-ice-background',
    'hover:from-normal-front', 'hover:to-normal-background',
    'hover:from-fighting-front', 'hover:to-fighting-background',
    'hover:from-poison-front', 'hover:to-poison-background',
    'hover:from-ground-front', 'hover:to-ground-background',
    'hover:from-flying-front', 'hover:to-flying-background',
    'hover:from-psychic-front', 'hover:to-psychic-background',
    'hover:from-bug-front', 'hover:to-bug-background',
    'hover:from-rock-front', 'hover:to-rock-background',
    'hover:from-ghost-front', 'hover:to-ghost-background',
    'hover:from-dragon-front', 'hover:to-dragon-background', ],
  theme: {
    extend: {
      colors: {
        'normal-front': '#D3D3D3', 
        'normal-background': '#A8A77A',
        'fire-front': '#FF6F61',
        'fire-background': '#FFC080',
        'water-front': '#3498DB',
        'water-background': '#56B3FA',
        'grass-front': '#3E8E41',
        'grass-background': '#8BC34A',
        'electric-front': '#F7DC6F',
        'electric-background': '#F2C464',
        'ice-front': '#45A0E6',
        'ice-background': '#66CCCC',
        'fighting-front': '#C12222',
        'fighting-background': '#FFC080',
        'poison-front': '#B565A7', 
        'poison-background': '#C51077',
        'ground-front': '#D2B48C', 
        'ground-background': '#FFC080',
        'flying-front': '#3A86FF',
        'flying-background': '#87CEEB',
        'psychic-front': '#FF69B4',
        'psychic-background': '#C9C3E3',
        'bug-front': '#8B9467',
        'bug-background': '#C6E2B5',
        'rock-front': '#666666',
        'rock-background': '#999999',
        'ghost-front': '#4C5154',
        'ghost-background': '#7A88A7',
        'dragon-front': '#0A6CF5',
        'dragon-background': '#87CEEB',
      },
    },
  },
  plugins: [],
};
